version: "3.0"
services:
  provider:
    build: ./Services/ProviderService
    container_name: provider
    ports:
      - "4010:4010"

  # Travel API
  travel:
    build: ./Services/TravelService
    container_name: travel
    ports:
      - "4011:4011"

  rooting:
    build: ./Services/RootingService
    container_name: rooting
    ports:
      - "4012:4012"

  payment:
    build: ./Services/PaymentService
    container_name: payment
    ports:
      - "4013:4013"
      
  booking:
    build: ./Services/BookingService
    container_name: booking
    ports:
      - "4014:4014"

  late:
    build: ./Services/LateService
    container_name: late_orchestrator
    ports:
      - "4017:4017"




  customer:
    build: ./Services/CustomerService
    container_name: customer
    ports:
      - "4018:4018"

  account:
    build: ./Services/AccountService
    container_name: account
    ports:
      - "4019:4019"

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    hostname: kafka
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://192.168.1.248:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "Late:1:1,status-booking:1:1,new-booking:1:1,rollback-booking:1:1,status-payment:1:1"
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks: 
  default: 
    external: 
      name: orchestrator_api-network
