version: "3.0"
services:
  provider:
    build: ./Services/ProviderService
    container_name: provider
    ports:
      - "4010:4010"

  # Travel API
  travel:
    build: ./Services/TravelService
    container_name: travel
    ports:
      - "4011:4011"
    
  rooting:
    build: ./Services/RootingService
    container_name: rooting
    ports:
      - "4012:4012"
    
  payment:
    build: ./Services/PaymentService
    container_name: payment
    ports:
      - "4013:4013"
      
  booking:
    build: ./Services/BookingService
    container_name: booking
    ports:
      - "4014:4014"

    
  price:
    build: ./Services/PriceService
    container_name: price
    ports:
      - "4015:4015"

  
  place:
    build: ./Services/PlaceService
    container_name: place
    ports:
      - "4016:4016"
      
  customer:
    build: ./Services/CustomerService
    container_name: customer
    ports:
      - "4018:4018"
 
 
