version: "3.0"
services:
  # Travel API
  travel:
    build: ./Services/TravelService
    container_name: travel_orchestrator
    ports:
      - "4001:4001"
    
  rooting:
    build: ./Services/RootingService
    container_name: rooting_orchestrator
    ports:
      - "4002:4002"
    
  payment:
    build: ./Services/PaymentService
    container_name: payment_orchestrator
    ports:
      - "4003:4003"
      
  booking:
    build: ./Services/BookingService
    container_name: booking_orchestrator
    ports:
      - "4004:4004"





      
  customer:
    build: ./Services/CustomerService
    container_name: customer_orchestrator
    ports:
      - "4008:4008"

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"


  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_BOB://kafka:29092,LISTENER_FRED://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka:29092,LISTENER_FRED://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "Late:1:1"
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


