version: "3.0"
services:
  # Travel API
  travel:
    build: ../Services/TravelService
    container_name: SNCF_travel
    ports:
      - "4001:4001"
    
  rooting:
    build: ../Services/RootingService
    container_name: SNCF_rooting
    ports:
      - "4002:4002"
    
  payment:
    build: ../Services/PaymentService
    container_name: SNCF_payment
    ports:
      - "4003:4003"
      
  booking:
    build: ../Services/BookingService
    container_name: SNCF_booking
    ports:
      - "4004:4004"

    
  price:
    build: ../Services/PriceService
    container_name: SNCF_price
    ports:
      - "4005:4005"

  
  place:
    build: ../Services/PlaceService
    container_name: SNCF_place
    ports:
      - "4006:4006"
      
  customer:
    build: ../Services/CustomerService
    container_name: SNCF_customer
    ports:
      - "4008:4008"

 
 
